app:
    resource: "@ErbolkingGuestBookBundle/Controller/"
    type:     annotation
    prefix:   /

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"